// Import all models to ensure they are registered
import './Permission'
import './Role'
import './User'
import './Organization'
import './Branch'
import './Governorate'
import './City'
import './RouteZone'
import './WorkSchedule'
import './Driver'
import './Vehicle'
import './Point'
import './Route'
import './RoutePoint'
import './RouteScheduleVehicle'
import './ZoneEvent'
import './PointVisit'
import './PointCompletion'
import './Unit'
import './MaterialCategory'
import './Material'
import './MaterialCategoryLink'
import './MaterialAttributeDefinition'
import './MaterialAttributeValue'
import './MaterialStock'
import './MaterialTransaction'
import './Survey'
import './SurveySubmission'
import './WebhookIncomingLog'
import './IncomingAtharEvent'
import './ContactSubmission'
import './Session'
import './VerificationTemplate'
import './WelcomeGreeting'
import './Campaign'
import './BulkSendJob'
import './Message'

// Re-export for convenience
export { default as Permission } from './Permission'
export { default as Role } from './Role'
export { default as User } from './User'
export { default as Organization } from './Organization'
export { default as Branch } from './Branch'
export { default as Governorate } from './Governorate'
export { default as City } from './City'
export { default as RouteZone } from './RouteZone'
export { default as WorkSchedule } from './WorkSchedule'
export { default as Driver } from './Driver'
export { default as Vehicle } from './Vehicle'
export { default as Point } from './Point'
export { default as Route } from './Route'
export { default as RoutePoint } from './RoutePoint'
export { default as RouteScheduleVehicle } from './RouteScheduleVehicle'
export { default as ZoneEvent } from './ZoneEvent'
export { default as PointVisit } from './PointVisit'
export { default as PointCompletion } from './PointCompletion'
export { default as Unit } from './Unit'
export { default as MaterialCategory } from './MaterialCategory'
export { default as Material } from './Material'
export { default as MaterialCategoryLink } from './MaterialCategoryLink'
export { default as MaterialAttributeDefinition } from './MaterialAttributeDefinition'
export { default as MaterialAttributeValue } from './MaterialAttributeValue'
export { default as MaterialStock } from './MaterialStock'
export { default as MaterialTransaction } from './MaterialTransaction'
export { default as Survey } from './Survey'
export { default as SurveySubmission } from './SurveySubmission'
export { default as WebhookIncomingLog } from './WebhookIncomingLog'
export { default as IncomingAtharEvent } from './IncomingAtharEvent'
export { default as ContactSubmission } from './ContactSubmission'
export { default as Session } from './Session'
export { default as VerificationTemplate } from './VerificationTemplate'
export { default as WelcomeGreeting } from './WelcomeGreeting'
export { default as Campaign } from './Campaign'
export { default as BulkSendJob } from './BulkSendJob'
export { default as Message } from './Message'

export type { IPermission } from './Permission'
export type { IRole } from './Role'
export type { IUser } from './User'
export type { IOrganization } from './Organization'
export type { IBranch } from './Branch'
export type { IGovernorate } from './Governorate'
export type { ICity } from './City'
export type { IRouteZone } from './RouteZone'
export type { IWorkSchedule, IWorkScheduleDay } from './WorkSchedule'
export type { IDriver } from './Driver'
export type { IVehicle } from './Vehicle'
export type { IPoint } from './Point'
export type { IRoute } from './Route'
export type { IRoutePoint } from './RoutePoint'
export type { IRouteScheduleVehicle } from './RouteScheduleVehicle'
export type { IZoneEvent } from './ZoneEvent'
export type { IPointVisit } from './PointVisit'
export type { IPointCompletion } from './PointCompletion'
export type { IUnit } from './Unit'
export type { IMaterialCategory } from './MaterialCategory'
export type { IMaterial } from './Material'
export type { IMaterialCategoryLink } from './MaterialCategoryLink'
export type { IMaterialAttributeDefinition } from './MaterialAttributeDefinition'
export type { IMaterialAttributeValue } from './MaterialAttributeValue'
export type { IMaterialStock } from './MaterialStock'
export type { IMaterialTransaction } from './MaterialTransaction'
export type { ISurvey } from './Survey'
export type { ISurveySubmission } from './SurveySubmission'
export type { IWebhookIncomingLog } from './WebhookIncomingLog'
export type { IIncomingAtharEvent } from './IncomingAtharEvent'
export type { IContactSubmission } from './ContactSubmission'
export type { ISession } from './Session'
export type { IVerificationTemplate } from './VerificationTemplate'
export type { IWelcomeGreeting } from './WelcomeGreeting'
export type { ICampaign } from './Campaign'
export type { IBulkSendJob } from './BulkSendJob'
export type { IMessage } from './Message'

