// Import all models to ensure they are registered
import './Permission'
import './Role'
import './User'
import './Organization'
import './Branch'
import './Driver'
import './Vehicle'
import './Point'
import './Route'
import './RoutePoint'
import './ZoneEvent'
import './PointVisit'
import './Unit'
import './MaterialCategory'
import './Material'
import './MaterialCategoryLink'
import './MaterialAttributeDefinition'
import './MaterialAttributeValue'
import './MaterialStock'
import './MaterialTransaction'
import './Survey'
import './SurveySubmission'

// Re-export for convenience
export { default as Permission } from './Permission'
export { default as Role } from './Role'
export { default as User } from './User'
export { default as Organization } from './Organization'
export { default as Branch } from './Branch'
export { default as Driver } from './Driver'
export { default as Vehicle } from './Vehicle'
export { default as Point } from './Point'
export { default as Route } from './Route'
export { default as RoutePoint } from './RoutePoint'
export { default as ZoneEvent } from './ZoneEvent'
export { default as PointVisit } from './PointVisit'
export { default as Unit } from './Unit'
export { default as MaterialCategory } from './MaterialCategory'
export { default as Material } from './Material'
export { default as MaterialCategoryLink } from './MaterialCategoryLink'
export { default as MaterialAttributeDefinition } from './MaterialAttributeDefinition'
export { default as MaterialAttributeValue } from './MaterialAttributeValue'
export { default as MaterialStock } from './MaterialStock'
export { default as MaterialTransaction } from './MaterialTransaction'
export { default as Survey } from './Survey'
export { default as SurveySubmission } from './SurveySubmission'

export type { IPermission } from './Permission'
export type { IRole } from './Role'
export type { IUser } from './User'
export type { IOrganization } from './Organization'
export type { IBranch } from './Branch'
export type { IDriver } from './Driver'
export type { IVehicle } from './Vehicle'
export type { IPoint } from './Point'
export type { IRoute } from './Route'
export type { IRoutePoint } from './RoutePoint'
export type { IZoneEvent } from './ZoneEvent'
export type { IPointVisit } from './PointVisit'
export type { IUnit } from './Unit'
export type { IMaterialCategory } from './MaterialCategory'
export type { IMaterial } from './Material'
export type { IMaterialCategoryLink } from './MaterialCategoryLink'
export type { IMaterialAttributeDefinition } from './MaterialAttributeDefinition'
export type { IMaterialAttributeValue } from './MaterialAttributeValue'
export type { IMaterialStock } from './MaterialStock'
export type { IMaterialTransaction } from './MaterialTransaction'
export type { ISurvey } from './Survey'
export type { ISurveySubmission } from './SurveySubmission'

