// Import all models to ensure they are registered
import './Permission'
import './Role'
import './User'
import './Municipality'
import './Driver'
import './Vehicle'
import './Point'
import './Route'
import './RoutePoint'
import './ZoneEvent'
import './PointVisit'

// Re-export for convenience
export { default as Permission } from './Permission'
export { default as Role } from './Role'
export { default as User } from './User'
export { default as Municipality } from './Municipality'
export { default as Driver } from './Driver'
export { default as Vehicle } from './Vehicle'
export { default as Point } from './Point'
export { default as Route } from './Route'
export { default as RoutePoint } from './RoutePoint'
export { default as ZoneEvent } from './ZoneEvent'
export { default as PointVisit } from './PointVisit'

export type { IPermission } from './Permission'
export type { IRole } from './Role'
export type { IUser } from './User'
export type { IMunicipality } from './Municipality'
export type { IDriver } from './Driver'
export type { IVehicle } from './Vehicle'
export type { IPoint } from './Point'
export type { IRoute } from './Route'
export type { IRoutePoint } from './RoutePoint'
export type { IZoneEvent } from './ZoneEvent'
export type { IPointVisit } from './PointVisit'

